global:
  scrape_interval: 15s  # Интервал сбора метрик

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']  # Сбор метрик с экспорта Nginx

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']  # Сбор метрик с экспорта PostgreSQL

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Сбор метрик с самого Prometheus